# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

addMat <- function(m1, m2) {
    .Call(`_binspp_addMat`, m1, m2)
}

multMat <- function(m1, m2) {
    .Call(`_binspp_multMat`, m1, m2)
}

intalphaC <- function(z_beta, alpha, alphabet, Wpix) {
    .Call(`_binspp_intalphaC`, z_beta, alpha, alphabet, Wpix)
}

aozC <- function(z, alpha, alphabet, u) {
    .Call(`_binspp_aozC`, z, alpha, alphabet, u)
}

logpXCbetC <- function(Y, CC, z_alpha, z_omega, alpha, alphabet, omega, omegabet, AreaW, integral) {
    .Call(`_binspp_logpXCbetC`, Y, CC, z_alpha, z_omega, alpha, alphabet, omega, omegabet, AreaW, integral)
}

KumulaVsechC <- function(CC, z_alpha, z_omega, alpha, alphabet, omega, omegabet, x_left, x_right, y_bottom, y_top) {
    .Call(`_binspp_KumulaVsechC`, CC, z_alpha, z_omega, alpha, alphabet, omega, omegabet, x_left, x_right, y_bottom, y_top)
}

PrioralphaC <- function(a, Prior_alpha_mean, Prior_alpha_SD) {
    .Call(`_binspp_PrioralphaC`, a, Prior_alpha_mean, Prior_alpha_SD)
}

PrioromegaC <- function(o, Prior_omega_mean, Prior_omega_SD) {
    .Call(`_binspp_PrioromegaC`, o, Prior_omega_mean, Prior_omega_SD)
}

PrioralphabetC <- function(a, Prior_alphavec_SD) {
    .Call(`_binspp_PrioralphabetC`, a, Prior_alphavec_SD)
}

PrioromegabetC <- function(o, Prior_omegavec_SD) {
    .Call(`_binspp_PrioromegabetC`, o, Prior_omegavec_SD)
}

StepbetC <- function(kappa, z_alpha, z_omega, alpha, salpha, alphabet, salphabet, omega, somega, omegabet, somegabet, Y, CC, logP, integral, integralrho, x_left, x_right, y_bottom, y_top, Wpix, AreaW, FScoef, Prior_alpha_mean, Prior_alpha_SD, Prior_omega_mean, Prior_omega_SD, Prior_alphavec_SD, Prior_omegavec_SD) {
    .Call(`_binspp_StepbetC`, kappa, z_alpha, z_omega, alpha, salpha, alphabet, salphabet, omega, somega, omegabet, somegabet, Y, CC, logP, integral, integralrho, x_left, x_right, y_bottom, y_top, Wpix, AreaW, FScoef, Prior_alpha_mean, Prior_alpha_SD, Prior_omega_mean, Prior_omega_SD, Prior_alphavec_SD, Prior_omegavec_SD)
}

row_add <- function(x, extraRow) {
    .Call(`_binspp_row_add`, x, extraRow)
}

rand_int <- function(min, max) {
    .Call(`_binspp_rand_int`, min, max)
}

StepMovePointC <- function(kappa, z_alpha, z_omega, alpha, alphabet, omega, omegabet, Y, CC, logP, integral, integralrho, x_left, x_right, y_bottom, y_top, AreaW, NewCenter) {
    .Call(`_binspp_StepMovePointC`, kappa, z_alpha, z_omega, alpha, alphabet, omega, omegabet, Y, CC, logP, integral, integralrho, x_left, x_right, y_bottom, y_top, AreaW, NewCenter)
}

