# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dgenpois_cpp <- function(x, lambda, theta, log_ret) {
    .Call('_binspp_dgenpois_cpp', PACKAGE = 'binspp', x, lambda, theta, log_ret)
}

dgp_comp_cpp <- function(lambda, theta) {
    .Call('_binspp_dgp_comp_cpp', PACKAGE = 'binspp', lambda, theta)
}

dgenpoisbin_cpp <- function(x, lambda, theta, mu, dgp) {
    .Call('_binspp_dgenpoisbin_cpp', PACKAGE = 'binspp', x, lambda, theta, mu, dgp)
}

intfun_cols_cpp <- function(c, omega, xr, yr) {
    .Call('_binspp_intfun_cols_cpp', PACKAGE = 'binspp', c, omega, xr, yr)
}

intfun_cpp <- function(c, omega, xr, yr) {
    .Call('_binspp_intfun_cpp', PACKAGE = 'binspp', c, omega, xr, yr)
}

mcmc_thom <- function(patlist, momslist, pat_bboxes, mom_bboxes, nsim, kappa0, a_kappa, b_kappa, proposal_s_kappa, alpha0, a_alpha, b_alpha, proposal_s_alpha, omega0, a_omega, b_omega, proposal_s_omega, name) {
    .Call('_binspp_mcmc_thom', PACKAGE = 'binspp', patlist, momslist, pat_bboxes, mom_bboxes, nsim, kappa0, a_kappa, b_kappa, proposal_s_kappa, alpha0, a_alpha, b_alpha, proposal_s_alpha, omega0, a_omega, b_omega, proposal_s_omega, name)
}

r_omega_cpp <- function(ostar, omega, X, C, lambda, theta, dgp, a_omega, b_omega) {
    .Call('_binspp_r_omega_cpp', PACKAGE = 'binspp', ostar, omega, X, C, lambda, theta, dgp, a_omega, b_omega)
}

r_lt_cpp <- function(lstar, tstar, lambda, theta, dl, X, C, omega, dgp, dgpstar, l_lambda, u_lambda, a_theta, b_theta) {
    .Call('_binspp_r_lt_cpp', PACKAGE = 'binspp', lstar, tstar, lambda, theta, dl, X, C, omega, dgp, dgpstar, l_lambda, u_lambda, a_theta, b_theta)
}

r_kappa_cpp <- function(kstar, kappa, m, win_size, a_kappa, b_kappa) {
    .Call('_binspp_r_kappa_cpp', PACKAGE = 'binspp', kstar, kappa, m, win_size, a_kappa, b_kappa)
}

update_omega <- function(omega, somega, X, C, lambda, theta, dgp, a_omega, b_omega) {
    .Call('_binspp_update_omega', PACKAGE = 'binspp', omega, somega, X, C, lambda, theta, dgp, a_omega, b_omega)
}

update_lt <- function(lambda, theta, stheta, dl, X, C, omega, dgp, l_lambda, u_lambda, a_theta, b_theta) {
    .Call('_binspp_update_lt', PACKAGE = 'binspp', lambda, theta, stheta, dl, X, C, omega, dgp, l_lambda, u_lambda, a_theta, b_theta)
}

update_kappa <- function(kappa, skappa, m, win_size, a_kappa, b_kappa) {
    .Call('_binspp_update_kappa', PACKAGE = 'binspp', kappa, skappa, m, win_size, a_kappa, b_kappa)
}

mcmc_lt <- function(lambda, theta, stheta, mus, dl, n, l_lambda, u_lambda, a_theta, b_theta) {
    .Call('_binspp_mcmc_lt', PACKAGE = 'binspp', lambda, theta, stheta, mus, dl, n, l_lambda, u_lambda, a_theta, b_theta)
}

update_P_cpp <- function(X, C, omega, lambda, theta, mus, dgp, p_count) {
    .Call('_binspp_update_P_cpp', PACKAGE = 'binspp', X, C, omega, lambda, theta, mus, dgp, p_count)
}

update_P_cpp_n <- function(X, C, omega, lambda, theta, mus, dgp, n_upd, p_count) {
    .Call('_binspp_update_P_cpp_n', PACKAGE = 'binspp', X, C, omega, lambda, theta, mus, dgp, n_upd, p_count)
}

move_C_cpp <- function(X, C, omega, lambda, theta, sd_c, dgp, m_count) {
    .Call('_binspp_move_C_cpp', PACKAGE = 'binspp', X, C, omega, lambda, theta, sd_c, dgp, m_count)
}

c_birth_cpp <- function(X, C, kappa, omega, lambda, theta, s_birth, dgp, b_count) {
    .Call('_binspp_c_birth_cpp', PACKAGE = 'binspp', X, C, kappa, omega, lambda, theta, s_birth, dgp, b_count)
}

c_death_cpp <- function(X, C, kappa, omega, lambda, theta, s_birth, dgp, d_count) {
    .Call('_binspp_c_death_cpp', PACKAGE = 'binspp', X, C, kappa, omega, lambda, theta, s_birth, dgp, d_count)
}

bdm <- function(X, C, ktmp, otmp, ltmp, ttmp, smove, sbirth, n_bdm, m_count, b_count, d_count) {
    invisible(.Call('_binspp_bdm', PACKAGE = 'binspp', X, C, ktmp, otmp, ltmp, ttmp, smove, sbirth, n_bdm, m_count, b_count, d_count))
}

